[package]
name = "tinysearch"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
version = "0.4.1"
edition = "2018"
description = "A tiny search engine for static websites"
license = "Apache-2.0/MIT"
documentation = "https://github.com/mre/tinysearch/blob/master/README.md"
homepage = "https://github.com/mre/tinysearch"

[dependencies]
structopt = "0.3.15"
tinysearch-shared = { path = "../shared", version = "0.2.1" }
log = "0.4.8"
serde_json = "1.0.55"
tinysearch-cuckoofilter = "0.4.1"
anyhow = "1.0"
tempfile = "3.1.0"
serde = "1.0.112"
serde_derive = "1.0.112"
lazy_static = "1.4.0"
pulldown-cmark = "0.7.1"
phf = "0.7.21"
includedir = "0.5.0"

[build-dependencies]
includedir_codegen = "0.5.0"