[package]
name = "tinysearch"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
version = "0.4.0"
edition = "2018"
description = "A tiny search engine for static websites"
license = "Apache-2.0/MIT"
documentation = "https://github.com/mre/tinysearch/blob/master/README.md"
homepage = "https://github.com/mre/tinysearch"

[dependencies]
structopt = "0.3.14"
tinysearch-shared = { path = "../shared", version = "0.2.1" }
log = "0.4.8"
serde_json = "1.0.51"
tinysearch-cuckoofilter = "0.4.1"
failure = "0.1.7"
tempdir = "0.3.7"
serde = "1.0.106"
serde_derive = "1.0.106"
lazy_static = "1.4.0"
pulldown-cmark = "0.7.0"
phf = "0.7.21"
includedir = "0.5.0"

[build-dependencies]
includedir_codegen = "0.5.0"