[package]
name = "tinysearch"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
version = "0.3.1"
edition = "2018"
description = "A tiny search engine for static websites"
license = "Apache-2.0/MIT"
documentation = "https://github.com/mre/tinysearch/blob/master/README.md"
homepage = "https://github.com/mre/tinysearch"

[dependencies]
structopt = "0.1.7"
structopt-derive = "0.1.6"
tinysearch-shared = { path = "../shared", version = "0.2.0" }
log = "0.4.6"
reqwest = "0.9.14"
semver = "0.9.0"
serde_json = "1.0.39"
flate2 = "1.0.7"
tar = "0.4.22"
strip_markdown = "0.1.0"
tinysearch-cuckoofilter = "0.4.0"
walkdir = "2.2.7"
failure = "0.1.5"
tempdir = "0.3.7"
serde = "1.0.90"
serde_derive = "1.0.90"
lazy_static = "1.3.0"
