language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - cargo install --force wasm-pack 
  - wasm-pack --version
  - cargo install --force --path bin
script:
  - tinysearch fixtures/index.json
