language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - cargo install --force wasm-pack || true
  - wasm-pack --version
script:
  - cd bin && cargo install --force --path .
  - tinysearch fixtures/index.json
