language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - cargo install --force wasm-pack || true
  - wasm-pack --version
script:
  - INPUT_DIR=fixtures make build
