[package]
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
name = "tinysearch"
version = "0.1.0"
edition = "2018"

[dependencies]
cuckoofilter = {git = "https://github.com/mre/rust-cuckoofilter" }
lazy_static = "1.3.0"
structopt = "0.2.15"
structopt-derive = "0.2.15"
bincode = "1.1.2"

[build-dependencies]
cuckoofilter = {git = "https://github.com/mre/rust-cuckoofilter" }
bincode = "1.1.2"

