[package]
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
name = "tinysearch"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.3.0"
bincode = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
wee_alloc = "0.4.3"
wasm-bindgen = "0.2.40"
bloomfilter = "0.0.12"

[build-dependencies]
bincode = "1.1.2"
walkdir = "2.2.7"
bloomfilter = "0.0.12"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 's'  # Optimize for size.
lto = true
codegen-units = 1
