[package]
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
name = "tinysearch"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cuckoofilter = {git = "https://github.com/mre/rust-cuckoofilter" }
lazy_static = "1.3.0"
bincode = "1.1.2"
serde = "1.0.89"
serde_json = "1.0.39"
wee_alloc = "0.4.3"
wasm-bindgen = "0.2.40"

[build-dependencies]
bincode = "1.1.2"
cuckoofilter = {git = "https://github.com/mre/rust-cuckoofilter" }
walkdir = "2.2.7"

[profile.release]
opt-level = 's'  # Optimize for size.
lto = true
codegen-units = 1