name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Runs every Thursday at 20:23 GMT to avoid bit rot
    - cron: "20 23 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v1
        with:
          rust-version: 

      - name: Set Rust version
        env:
          RUST_VERSION: ${{ matrix.rust }}
        run: rustup default ${RUST_VERSION}

      - if: matrix.rust == 'stable'
        run: rustup component add clippy

      - if: matrix.rust == 'stable'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Install wasm-pack
        run:
          cargo install --force --git https://github.com/mre/wasm-pack.git --branch first-class-bins

      - name: Print wasm-pack version
        run: wasm-pack --version

      - name: Build & install tinysearch
        run: cargo install --force --path bin

      - name: Build wasm package
        run: RUST_LOG=debug tinysearch fixtures/index.json

      - name: Audit for Security Vulnerabilities
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --no-deps

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: target/release/tinysearch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
